package com.github.saku0817.combatcoresystems.model;

public enum StatKey {
    HP_FLAT, HP_PERCENT, ATK_FLAT, ATK_PERCENT, DEF_FLAT, DEF_PERCENT,
    CRIT_RATE, CRIT_DAMAGE, HEALING_POWER, COOLDOWN, ATTACK_SPEED,
    FIRE_DAMAGE, FIRE_RESISTANCE, WATER_DAMAGE, WATER_RESISTANCE,
    WIND_DAMAGE, WIND_RESISTANCE, THUNDER_DAMAGE, THUNDER_RESISTANCE,
    MOON_DAMAGE, MOON_RESISTANCE, DEF_DOWN,
    FIRE_RESISTANCE_DOWN,
    WATER_RESISTANCE_DOWN,
    WIND_RESISTANCE_DOWN,
    THUNDER_RESISTANCE_DOWN,
    MOON_RESISTANCE_DOWN
}
